services:
  user-service:
    build:
      context: ./services/user-service
    container_name: user-service
    expose:
      - "8000"

  product-service:
    build:
      context: ./services/product-service
    container_name: product-service
    expose:
      - "8000"

  order-service:
    build:
      context: ./services/order-service
    container_name: order-service
    environment:
      USER_SERVICE_URL: http://user-service:8000
      PRODUCT_SERVICE_URL: http://product-service:8000
    depends_on:
      - user-service
      - product-service
    expose:
      - "8000"

  api-gateway:
    build:
      context: .
      dockerfile: api-gateway/Dockerfile
    container_name: api-gateway
    depends_on:
      - user-service
      - product-service
      - order-service
    ports:
      - "8080:80"
