services:
  user-service:
    image: akshat004b/user-service:v4
    build:
      context: ./services/user-service
    container_name: user-service
    expose:
      - "8000"

  product-service:
    image: akshat004b/product-service:v5
    build:
      context: ./services/product-service
    container_name: product-service
    expose:
      - "8000"

  order-service:
    image: akshat004b/order-service:v5
    build:
      context: ./services/order-service
    container_name: order-service
    environment:
      USER_SERVICE_URL: http://user-service:8000
      PRODUCT_SERVICE_URL: http://product-service:8000
    depends_on:
      - user-service
      - product-service
    expose:
      - "8000"

  api-gateway:
    image: akshat004b/api-gateway:v3
    build:
      context: .
      dockerfile: api-gateway/Dockerfile
    container_name: api-gateway
    depends_on:
      - user-service
      - product-service
      - order-service
    volumes:
      - ./frontend:/usr/share/nginx/html:ro
      - ./api-gateway/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "8080:80"
