apiVersion: v1
kind: ConfigMap
metadata:
  name: api-gateway-nginx-config
data:
  nginx.conf: |
    events {}

    http {
      server {
        listen 80;

        location /health {
          default_type application/json;
          return 200 '{"status":"ok"}';
        }

        location /users {
          proxy_pass http://user-service:80;
        }

        location /products {
          proxy_pass http://product-service:80;
        }

        location /orders {
          proxy_pass http://order-service:80;
        }
      }
    }
