{{- if .Values.platform.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "ecommerce-platform.fullname" . }}
  labels:
    {{- include "ecommerce-platform.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "ecommerce-platform.selectorLabels" . | nindent 4 }}
{{- end }}
